-- ╭—————╮__1.ENGLISH______╭—————┬—————┬—————┬—————┬—————┬—————┬—————┬—————┬—————┬———————╮
-- │  ⎋  │  1  │  2  │  3  │  4  │  5  │  6  │  7  │  8  │  9  │  0  │  -  │  =  │    ⌫  │
-- ├—————┴—┬———┴—┬———┴—┬———┴—┬———┴—┬———┴—┬———┴—┬———┴—┬———┴—┬———┴—┬———┴—┬———┴—┬———┴—┬—————┤
-- │  ⇥    │  q  │  w  │  e  │  r  │  t  │  y  │  u  │  i  │  o  │  p  │  [  │  ]  │  ↩  │
-- ├———————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴╮    │
-- │  ⇪     │  a  │  s  │  d  │  f  │  g  │  h  │  j  │  k  │  l  │  ;  │  '  │  \  │    │
-- ├————————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴┬————┴—————┴————┤
-- │  ⇧      │  z  │  x  │  c  │  v  │  b  │  n  │  m  │  ,  │  .  │  /  │            ⇧  │
-- ├————————┬┴————┬┴—————┼—————┴—————┴—————┴—————┴—————┼—————┴┬————┴┬————┴———————————————╯
-- │  ⌃     │  ⌥  │   ⌘  │             ␣               │  ⌘   │  ⌥  │
-- ╰————————┴—————┴——————┴—————————————————————————————┴——————┴—————╯
-- ⎋: escape
-- 1: YouTube — Navigate to 10% of video
-- 2: YouTube — Navigate to 20% of video
-- 3: YouTube — Navigate to 30% of video
-- 4: YouTube — Navigate to 40% of video
-- 5: YouTube — Navigate to 50% of video
-- 6: YouTube — Navigate to 60% of video
-- 7: YouTube — Navigate to 70% of video
-- 8: YouTube — Navigate to 80% of video
-- 9: YouTube — Navigate to 90% of video
-- 0: YouTube — Navigate to 0% of video
-- t: YouTube — Theatre mode
-- i: YouTube — Minimize video
-- ↩: Music — Play selected song from beginning
-- f: 🌐 — Go Full Screen Video
-- g + g: 🌐 Vim — Go Window Top
-- j: YouTube — 10sec back
-- k: YouTube — play/pause
-- l: YouTube — 10sec forward
-- z: 🌐 Vim — Mark Links
-- x: 🌐 Vim — Focus text input
-- c: YouTube — subtitles
-- m: 🌐 Vim — Mute Tab
-- ␣: 📁 — Show Preview
--    Music — Play/Pause
--    Fork — Show changes Preview
-- double ⇧: ℝ — Command Pallette
-- ↑: Telegram — edit last message
--    Iina — sound up 5%
-- ↓: Iina — sound down 5%
-- →: YouTube — seek forward 5sec
--    Iina — seek forward 5sec
-- ←: YouTube — seek backward 5sec
--    Iina — seek backward 5sec

return {}
