return {
--    ╭—————╮
--    │  Q  │    quit / pageup
--    ╰—————╯
--
--         karabiner: ⇪q → PgUp
--
--———————— chord ┬ en | ru | el ┬
--           q   │ q    й    ;  │
--———————————————┼——————————————┼——————————————————————————————————
--          ⇪q   │    PgUp      │
--          ⇧q   │ Q    Й    :  │
--          ⌃q   │              │ ℝ — stop all
{ chord =  "⌥q",                  app="Music"},
--          ⌘q   │              │  — close app
--———————————————┼——————————————┼——————————————————————————————————
--         ⇪⇧q   │    ⇧PgUp     │  — page of text up
--         ⇪⌃q   │    ⌃PgUp     │ 📝 — scroll up (without moving caret)
--               │              │ 🌐 — go to tab to the left
--         ⇪⌥q   │    ⌥PgUp     │
--         ⌘⇧q   │              │  — log out from account with closing of all apps
--         ⇧⌃q   │              │  — log out with dialogs (handled by macOS)
--         ⇧⌥q   │              │
--         ⇧⌘q   │              │
{ chord = "⌃⌥q",                  app = "Music" },
--         ⌃⌘q   │              │  — logout
--         ⌥⌘q   │              │
--———————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧⌃q   │              │
--        ⇪⇧⌥q   │              │
--        ⇪⇧⌘q   │              │
--        ⇪⌃⌥q   │              │
--        ⇪⌃⌘q   │              │
--        ⇪⌥⌘q   │              │
--        ⇧⌃⌥q   │              │
--        ⇧⌃⌘q   │              │
--        ⇧⌥⌘q   │              │  — close all other apps
--        ⌃⌥⌘q   │              │
--———————————————┼——————————————┼——————————————————————————————————
--       ⇪⇧⌃⌥q   │              │
--       ⇪⇧⌃⌘q   │              │
--       ⇪⇧⌥⌘q   │              │
--       ⇪⌃⌥⌘q   │              │
--       ⇧⌃⌥⌘q   │              │
--———————————————┼——————————————┼——————————————————————————————————
--      ⇪⇧⌃⌥⌘q   │              │
--               ┴              ┴
}
