return {
--    ╭—————╮
--    │  ⇥  │    tab / return
--    ╰—————╯
--
--         karabiner: ⇪⇥ → ↩
--
--———————— chord ┬ en | ru | el ┬
--           ⇥   │       ⇥      │
--———————————————┼——————————————┼——————————————————————————————————
--          ⇪⇥   │       ↩      │  — enter / return
--          ⇧⇥   │              │  — select previous element or move text block left
--          ⌃⇥   │              │  — switch tab forward
--          ⌥⇥   │              │  —switch the app windows with AltTab app
--          ⌘⇥   │              │  — switch between open windows
--———————————————┼——————————————┼——————————————————————————————————
--         ⇪⇧⇥   │              │
--         ⇪⌃⇥   │              │  — open context menu
--               │              │ ℝ — generate (alternative to cmd + n)
--         ⇪⌥⇥   │              │
--         ⌘⇧⇥   │              │  — switch between open windows backwards
--         ⇧⌃⇥   │              │  — go to previous tab
--         ⇧⌥⇥   │              │
--         ⇧⌘⇥   │              │
{ chord = "⌃⌥⇥",                  fn = "translate_to_english" },
--         ⌃⌘⇥   │              │
--         ⌥⌘⇥   │              │
--———————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧⌃⇥   │              │
--        ⇪⇧⌥⇥   │              │
--        ⇪⇧⌘⇥   │              │
--        ⇪⌃⌥⇥   │              │
--        ⇪⌃⌘⇥   │              │
--        ⇪⌥⌘⇥   │              │ Fork — commit and push changes
--        ⇧⌃⌥⇥   │              │
--        ⇧⌃⌘⇥   │              │
--        ⇧⌥⌘⇥   │              │
--        ⌃⌥⌘⇥   │              │
--———————————————┼——————————————┼——————————————————————————————————
--       ⇪⇧⌃⌥⇥   │              │
--       ⇪⇧⌃⌘⇥   │              │
--       ⇪⇧⌥⌘⇥   │              │
--       ⇪⌃⌥⌘⇥   │              │
--       ⇧⌃⌥⌘⇥   │              │
--               ┴              ┴
}
