return {
--    ╭—————╮
--    │  0  │    F10 / last / default
--    ╰—————╯
--
--
--———————— chord ┬ en | ru | el ┬———————— app — function ————————————————————
--           0   │      0       │     YouTube — Navigate to 0% of video
--———————————————┼——————————————┼——————————————————————————————————
--          ⇪0   │     F10      │
--          ⇧0   │ )    )    )  │
--          ⌃0   │              │      VSCode — go to last tab
--          ⌥0   │ →    →    →  │
--          ⌘0   │              │     Browser — Reset zoom
--               │              │      VSCode — focus into primary sidebar
--               │              │    Telegram — focus Saved Messages
--               │              │       Music — Show/Hide Music window
--               │              │        Fork — navigate to HEAD
--               │              │        IINA — set window-scale 0.5
--               │              │        Mail — show the Mail viewer window
--———————————————┼——————————————┼——————————————————————————————————
--         ⇪⇧0   │     ⇧F10     │      VSCode — show editor context menu
--         ⇪⌃0   │     ⌃F10     │
--         ⇪⌥0   │     ⌥F10     │
--         ⇪⌘0   │     ⌘F10     │
--         ⇧⌃0   │              │
--         ⇧⌥0   │ ›    ›    ύ  │
--         ⇧⌘0   │              │
--         ⌃⌥0   │              │
--         ⌃⌘0   │              │        Mail — show the Mail Activity window
--         ⌥⌘0   │              │    Telegram — focus Saved Messages
--———————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧⌃0   │     ⇧⌃F10    │
--        ⇪⇧⌥0   │     ⇧⌥F10    │
--        ⇪⇧⌘0   │     ⇧⌘F10    │
--        ⇪⌃⌥0   │     ⌃⌥F10    │
--        ⇪⌃⌘0   │     ⌃⌘F10    │
--        ⇪⌥⌘0   │     ⌥⌘F10    │
--        ⇧⌃⌥0   │              │
--        ⇧⌃⌘0   │              │
--        ⇧⌥⌘0   │              │
--        ⌃⌥⌘0   │              │
--               ┴              ┴
}
