return {
--    ╭—————╮
--    │  4  │    4th / F4 / Edit
--    ╰—————╯
--
--
--———————— chord ┬ en | ru | el ┬————————————— app — function ————————————————————
--           4   │      4       │          YouTube — navigate to 40% of video
--———————————————┼——————————————┼——————————————————————————————————
--          ⇪4   │     F4       │           VSCode — go to next found occurrence
--               │              │                 — open to edit
--          ⇧4   │ $    ;    $  │
--          ⌃4   │              │           VSCode — go to tab 4
--          ⌥4   │              │ ???
--          ⌘4   │              │            Rider — focus build window
--               │              │           Finder — View in gallery
--               │              │          Browser — Open 4th tab
--               │              │ Activity Manager — Open/focus GPU history window
--               │              │         Telegram — focus 4th folder or chat
--          ⇥4   │     ⌘=       │          Browser — Zoom in
--               │              │            Rider — expand code block
--———————————————┼——————————————┼——————————————————————————————————
--         ⇪⇧4   │     ⇧F4      │
--         ⇪⌃4   │     ⌃F4      │
--         ⇪⌥4   │     ⌥F4      │
--         ⇪⌘4   │     ⌘F4      │
--         ⇧⌃4   │              │
--         ⇧⌥4   │              │
--         ⇧⌘4   │              │            Shotr — start getting screenshot
{ chord = "⌃⌥4",                                fn = "audio.external" },
--         ⌃⌘4   │              │
--         ⌥⌘4   │              │
--———————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧⌃4   │    ⇧⌃F4      │
--        ⇪⇧⌥4   │    ⇧⌥F4      │
--        ⇪⇧⌘4   │    ⇧⌘F4      │
--        ⇪⌃⌥4   │    ⌃⌥F4      │
--        ⇪⌃⌘4   │    ⌃⌘F4      │
--        ⇪⌥⌘4   │    ⌥⌘F4      │
--        ⇧⌃⌥4   │              │
--        ⇧⌃⌘4   │              │
--        ⇧⌥⌘4   │              │
--        ⌃⌥⌘4   │              │
--               ┴              ┴
}
