return {
--    ╭————————╮
--    │     ⌫  │    backspace / delete
--    ╰————————╯
--
--
--——————— chord ┬ en | ru | el ┬————————— app — function ————————————————————
--          ⌫   │      ⌫       │
--——————————————┼——————————————┼——————————————————————————————————
--         ⇪⌫   │      ⌦       │             — delete right
--         ⇧⌫   │      ⌫       │
--         ⌃⌫   │              │
--         ⌥⌫   │              │             — remove word to the left
--         ⌘⌫   │              │             — delete
--              │              │        Rider — delete line
--              │              │       VSCode — delete line
--——————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧⌫   │     ⇧⌦       │        Rider — delete line
--        ⇪⌃⌫   │     ⌃⌦       │
--        ⇪⌥⌫   │     ⌥⌦       │             — delete word to the right
--        ⇪⌘⌫   │     ⌘⌦       │
--        ⇧⌃⌫   │              │
--        ⇧⌥⌫   │              │
--        ⇧⌘⌫   │              │        Rider — go to last edit place
--              │              │       VSCode — go to last edit place
--              │              │      Browser — show clear history dialog
--        ⌃⌥⌫   │              │
--        ⌃⌘⌫   │              │
--        ⌥⌘⌫   │              │
--——————————————┼——————————————┼——————————————————————————————————
--       ⇪⇧⌃⌫   │              │
--       ⇪⇧⌥⌫   │              │
--       ⇪⇧⌘⌫   │              │
--       ⇪⌃⌥⌫   │              │
--       ⇪⌃⌘⌫   │              │
--       ⇪⌥⌘⌫   │              │
--       ⇧⌃⌥⌫   │              │
--       ⇧⌃⌘⌫   │              │
--       ⇧⌥⌘⌫   │              │
--       ⌃⌥⌘⌫   │              │
--              ┴              ┴
}
