return {
--    ╭—————╮
--    │  D  │    right / duplicate / delete
--    ╰—————╯
--
--———————— chord ┬ en | ru | el ┬———————— app — function ————————————————————
--           d   │ d    в    δ  │            — letter 'd'
--          dd   │              │  BrowserVim — go forward
--———————————————┼——————————————┼————————————————————————————————————————————
--          ⇪d   │      →       │            — go right
--          ⇧d   │ D    В    Δ  │
--          ⌃d   │              │       Rider — start debug
--               │              │      VSCode — start debug
--          ⌥d   │      ⌥→      │            — jump a word to the right
--               │              │     YouTube — jump to chapter to the right
--          ⌘d   │              │            — duplicate
--               │              │       Rider — duplicate line
--               │              │      VSCode — duplicate line
--               │              │ GoogleMeets — toggle microphone
--———————————————┼——————————————┼————————————————————————————————————————————
--         ⇪⇧d   │      ⇧→      │            — select letter to the right
--         ⇪⌃d   │      ⌃→      │            — jump to workspace to the right
--         ⇪⌥d   │      ⌥→      │            — jump a word to the right
--               │              │     YouTube — jump to chapter to the right
--         ⇪⌘d   │      ⌘→      │            — end/jump to end of line
--         ⇧⌃d   │              │
--         ⇧⌥d   │              │
--         ⇧⌘d   │              │      VSCode — focus Run and Debug panel
--               │              │      Finder — go to Desktop
--               │              │        Mail — send emails
--         ⌃⌥d   │              │      VSCode — focus Run and Debug panel
{ chord = "⌃⌥d",                           fn = "window.right" },
--         ⌃⌘d   │              │            — look up the selected word
--         ⌥⌘d   │              │            — show/hide Dock
--———————————————┼——————————————┼————————————————————————————————————————————
--        ⇪⇧⌃d   │  next_track  │            — go to next track
--        ⇪⇧⌥d   │     ⇧⌥→      │            — select word to the right
--        ⇪⇧⌘d   │     ⇧⌘→      │            — select line till the end
--        ⇪⌃⌥d   │     ⌃⌥→      │
--        ⇪⌃⌘d   │     ⌃⌘→      │      VSCode — move editor to next group
--        ⇪⌥⌘d   │     ⌥⌘→      │       Music — seek forward;
--               │              │      VSCode — go to next tab;
--               │              │       iTerm — focus pane to the right
--        ⇧⌃⌥d   │              │
--        ⇧⌃⌘d   │              │
--        ⇧⌥⌘d   │              │
--        ⌃⌥⌘d   │              │
--               ┴              ┴
}│
