return {
--    ╭—————╮
--    │  D  │    right / duplicate / delete
--    ╰—————╯
--
--         karabiner: ⇪d → →
--                    ⇪⇧⌃d → vk_consumer_next
--                    ⇧⌃⌥d → ⌥⌦
--
--———————— chord ┬ en | ru | el ┬
--           d   │ d    в    δ  │
--          dd   │              │ 🌐 Vim — go forward
--———————————————┼——————————————┼——————————————————————————————————
--          ⇪d   │      →       │  — right
--          ⇧d   │ D    В    Δ  │
--          ⌃d   │              │ ℝ, 📝 — debug
--          ⌥d   │      ⌥→      │  — jump a word to the right
--               │              │ YouTube — jump to chapter to the right
--          ⌘d   │              │  — duplicate
--               │              │ ℝ — duplicate line
--               │              │ Google Meets — toggle microphone
--———————————————┼——————————————┼——————————————————————————————————
--         ⇪⇧d   │      ⇧→      │  — select letter to the right
--         ⇪⌃d   │      ⌃→      │  — jump to workspace to the right
--         ⇪⌥d   │      ⌥→      │  — jump a word to the right
--               │              │ YouTube — jump to chapter to the right
--         ⇪⌘d   │      ⌘→      │  — end/jump to end of line
--         ⇧⌃d   │      ⌦       │  — delete symbol to the right
--         ⇧⌥d   │      ⌥⌦      │  delete word to the right
--         ⇧⌘d   │              │ 📝 — focus Run and Debug panel
--               │              │ 📁 — go to Desktop
--               │              │ Mail — send emails
--         ⌃⌥d   │              │ 📝 — focus Run and Debug panel
{ chord = "⌃⌥d",                  fn = "window.right" },
--         ⌃⌘d   │              │  — look up the selected word
--         ⌥⌘d   │              │  — show/hide Dock
--———————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧⌃d   │  next_track  │  — vk_consumer_next
--        ⇪⇧⌥d   │     ⇧⌥→      │  — select word to the right
--        ⇪⇧⌘d   │     ⇧⌘→      │  — select line till the end
--        ⇪⌃⌥d   │     ⌃⌥→      │
--        ⇪⌃⌘d   │     ⌃⌘→      │ 📝 — move editor to next group
--        ⇪⌥⌘d   │     ⌥⌘→      │ Music — seek forward;
--               │              │ 📝 — go to next tab;
--               │              │ iTerm — focus pane to the right
--        ⇧⌃⌥d   │      ⌥⌦      │ ⌦ — delete word to the right
--        ⇧⌃⌘d   │              │
--        ⇧⌥⌘d   │              │
--        ⌃⌥⌘d   │              │
--               ┴              ┴
}
