return {
--    ╭—————╮
--    │  ↓  │    down
--    ╰—————╯
--
--
--———————— chord ┬ en | ru | el ┬—————————— app — function ————————————————————
--           ↓   │      ↓       │          IINA — sound down 5%
--———————————————┼——————————————┼——————————————————————————————————
--          ⇪↓   │      ↓       │          IINA — sound down 5%
--          ⇧↓   │              │              — select text down one page
--          ⌃↓   │              │              — show windows of current app
--          ⌥↓   │              │              — move line down
--               │              │       YouTube — previous chapter in current video
--               │              │         Rider — shrink selection
--          ⌘↓   │              │         Music — decrease volume
--               │              │         Rider — edit source
--———————————————┼——————————————┼——————————————————————————————————
--         ⇪⇧↓   │              │
--         ⇪⌃↓   │              │
--         ⇪⌥↓   │              │
--         ⇪⌘↓   │              │
--         ⇧⌃↓   │              │
--         ⇧⌥↓   │              │        VSCode — move line down
--         ⇧⌘↓   │ key_light_dn │ illumination_decrement
{ chord = "⌃⌥↓",                             fn = "window.set_all_to_default" },
--         ⌃⌘↓   │              │
--         ⌥⌘↓   │              │        VSCode — create cursor down
--———————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧⌃↓   │              │
--        ⇪⇧⌥↓   │              │
--        ⇪⇧⌘↓   │              │
--        ⇪⌃⌥↓   │              │
--        ⇪⌃⌘↓   │              │
--        ⇪⌥⌘↓   │              │
--        ⇧⌃⌥↓   │              │
--        ⇧⌃⌘↓   │              │
--        ⇧⌥⌘↓   │              │
--        ⌃⌥⌘↓   │              │
--               ┴              ┴
}
