return {
--    ╭—————╮
--    │  I  │
--    ╰—————╯
--
--
--———————— chord ┬ en | ru | el ┬————————————— app — function ————————————————————
--           i   │ i    ш    ι  │          YouTube — Minimize video
--———————————————┼——————————————┼——————————————————————————————————
--          ⇪i   │              │
--          ⇧i   │ I    Ш    Ι  │
--          ⌃i   │              │
--          ⌥i   │ і    і    †  │
--          ⌘i   │              │ Activity Manager — Inspect process
--———————————————┼——————————————┼——————————————————————————————————
--         ⇪⇧i   │              │
--         ⇪⌃i   │              │
--         ⇪⌥i   │              │
--         ⇪⌘i   │              │
--         ⇧⌃i   │              │
--         ⇧⌥i   │              │
--         ⇧⌘i   │              │           VSCode — open agent chat
{ chord = "⌃⌥i",                                fn = "info.show_shortcuts" },
--         ⌃⌘i   │              │           VSCode — open chat
--         ⌥⌘i   │              │          Browser — open Developer Tools
--               │              │             Mail — append selected emails to email
--———————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧⌃i   │              │
--        ⇪⇧⌥i   │              │
--        ⇪⇧⌘i   │              │
--        ⇪⌃⌥i   │              │
--        ⇪⌃⌘i   │              │
--        ⇪⌥⌘i   │              │
--        ⇧⌃⌥i   │              │
--        ⇧⌃⌘i   │              │
--        ⇧⌥⌘i   │              │
--        ⌃⌥⌘i   │              │
--               ┴              ┴
}
