return {
--    ╭—————╮
--    │  J  │    jump / journal
--    ╰—————╯
--
--         karabiner: no
--
--——————— chord ┬ en | ru | el ┬
--          j   │ j    о    ξ  │ YouTube 10sec back
--——————————————┼——————————————┼——————————————————————————————————
--         ⇪j   │              │
--         ⇧j   │ J    О    Ξ  │
--         ⌃j   │              │
--         ⌥j   │ „    „    ≤  │
--         ⌘j   │              │ Music — open View Options window
--——————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧j   │              │
--        ⇪⌃j   │              │
--        ⇪⌥j   │              │
--        ⇪⌘j   │              │
--        ⇧⌃j   │              │
--        ⇧⌥j   │              │
--        ⇧⌘j   │              │ Mail — move to Junk
--        ⌃⌥j   │              │ Day One → create journal entry
--        ⌃⌘j   │              │
--        ⌥⌘j   │              │ Yandex — JavaScript console
--              │              │ Mail — erase junk mail
--——————————————┼——————————————┼——————————————————————————————————
--       ⇪⇧⌃j   │              │
--       ⇪⇧⌥j   │              │
--       ⇪⇧⌘j   │              │
--       ⇪⌃⌥j   │              │
--       ⇪⌃⌘j   │              │
--       ⇪⌥⌘j   │              │
--       ⇧⌃⌥j   │              │
--       ⇧⌃⌘j   │              │
--       ⇧⌥⌘j   │              │
--       ⌃⌥⌘j   │              │
--              ┴              ┴
}
