return {
--    ╭—————╮
--    │  M  │    minimize / mute
--    ╰—————╯
--
--
--——————— chord ┬ en | ru | el ┬—————————— app — function ————————————————————
--          m   │ m    ь    μ  │   Browser Vim — Mute Tab
--              │              │          IINA — cycle mute
--——————————————┼——————————————┼——————————————————————————————————
--         ⇪m   │              │
--         ⇧m   │ M    Ь    Μ  │
--         ⌃m   │              │
--         ⌥m   │ −    −    ’  │
--         ⌘m   │              │              — minimize window
--——————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧m   │              │
--        ⇪⌃m   │              │
--        ⇪⌥m   │              │
--        ⇪⌘m   │              │
--        ⇧⌃m   │              │
--        ⇧⌥m   │ •    •    Ύ  │
--        ⇧⌘m   │              │         Rider — new project window
--        ⌃⌥m   │              │
--        ⌃⌘m   │              │
--        ⌥⌘m   │              │         Music — open/close MiniPlayer
--              │              │         Rider — extract method
--              │              │          Mail — move to predicted mailbox
--——————————————┼——————————————┼——————————————————————————————————
--       ⇪⇧⌃m   │              │
--       ⇪⇧⌥m   │              │
--       ⇪⇧⌘m   │              │
--       ⇪⌃⌥m   │              │
--       ⇪⌃⌘m   │              │
--       ⇪⌥⌘m   │              │
--       ⇧⌃⌥m   │              │
--       ⇧⌃⌘m   │              │
--       ⇧⌥⌘m   │              │
--       ⌃⌥⌘m   │              │
--              ┴              ┴
}
