return {
--    ╭—————╮
--    │  N  │    notes / new
--    ╰—————╯
--
--
--———————— chord ┬ en | ru | el ┬————————— app — function ————————————————————
--           n   │ n    т    ν  │
--———————————————┼——————————————┼——————————————————————————————————
{ chord =  "⇪n",                           app = "Visual Studio Code" },
--          ⇧n   │ N    Т    Ν  │
--          ⌃n   │              │
--          ⌥n   │ ‘    ‘    ‘  │         Mail — open a new Mail viewer window
--          ⌘n   │              │             — new window
--               │              │        Music — create a new playlist
--               │              │         Mail — start a new email
--               │              │       VSCode — new file
--———————————————┼——————————————┼——————————————————————————————————
--         ⇪⇧n   │              │
--         ⇪⌃n   │              │
--         ⇪⌥n   │              │
--         ⇪⌘n   │              │
--         ⇧⌃n   │              │
--         ⇧⌥n   │ ˜    ˜    Ό  │
--         ⇧⌘n   │              │         Mail — get new emails
--               │              │      Browser — open new Private Window
--               │              │        Music — create a playlist from selection
--         ⌃⌥n   │              │
--         ⌃⌘n   │              │
--         ⌥⌘n   │              │        Music — create a Smart Playlist
--                              │         Mail — open a new tab in Mail viewer
--                              │            ℝ — inline
--———————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧⌃n   │              │
--        ⇪⇧⌥n   │              │
--        ⇪⇧⌘n   │              │
--        ⇪⌃⌥n   │              │
--        ⇪⌃⌘n   │              │
--        ⇪⌥⌘n   │              │
--        ⇧⌃⌥n   │              │
--        ⇧⌃⌘n   │              │
--        ⇧⌥⌘n   │              │
--        ⌃⌥⌘n   │              │
--               ┴              ┴
}
