return {
--    ╭—————╮
--    │  Q  │    quit / pageup / backspace
--    ╰—————╯
--
--
--———————— chord ┬ en | ru | el ┬————————— app — function ————————————————————
--           q   │ q    й    ;  │
--———————————————┼——————————————┼————————————————————————————————————
--          ⇪q   │    PgUp      │
--          ⇧q   │ Q    Й    :  │   Browser Vimt — go to root domain
--          ⌃q   │              │         Rider — stop all/build
--               │              │        VSCode — quick view popup
--          ⌥q   │      ⌫       │              — delete letter to the left
--          ⌘q   │              │              — close app
--          ⇥q   │     ⇧⌘⌫      │         Rider — go to last edit place
--               │              │        VSCode — go to last edit place
--               │              │       Browser — show clear history dialog
--———————————————┼——————————————┼————————————————————————————————————
--         ⇪⇧q   │    ⇧PgUp     │              — page of text up
--         ⇪⌃q   │    ⌃PgUp     │        VSCode — scroll up (without moving caret)
--               │              │       Browser — go to tab to the left
--         ⇪⌥q   │      ⌥⌫      │              — delete word to the left
--               │              │         Rider — delete line
--               │              │        VSCode — delete line
--         ⇪⌘q   │      ⌘⌫      │              — delete
--               │              │         Rider — delete line
--               │              │        VSCode — delete line
--         ⇧⌃q   │       ⌫      │              — delete symbol to the left
--         ⇧⌥q   │              │
--         ⇧⌘q   │              │              — log out from account with closing of all apps
{ chord = "⌃⌥q",                            app = "Music" },
--         ⌃⌘q   │              │              — lock screen
--         ⌥⌘q   │      ⌘⌫      │              — delete
--               │              │         Rider — delete line
--               │              │        VSCode — delete line
--———————————————┼——————————————┼————————————————————————————————————
--        ⇪⇧⌃q   │      ⇪p      │ H — open Music app
--        ⇪⇧⌥q   │              │
--        ⇪⇧⌘q   │     ⇧⌘⌫      │         Rider — go to last edit place
--               │              │        VSCode — go to last edit place
--        ⇪⌃⌥q   │     ⇧⌘⌫      │         Rider — go to last edit place
--               │              │        VSCode — go to last edit place
--        ⇪⌃⌘q   │              │
--        ⇪⌥⌘q   │              │
--        ⇧⌃⌥q   │              │
--        ⇧⌃⌘q   │              │
--        ⇧⌥⌘q   │              │              — close all other apps
--        ⌃⌥⌘q   │              │
--               ┴              ┴
}
