return {
--    ╭—————╮
--    │  ␣  │    Raycast / language toggle
--    ╰—————╯
--
--
--——————— chord ┬ en | ru | el ┬—————————— app — function ————————————————————
--          ␣   │      ␣       │        Finder — Show Preview
--              │              │         Music — Play/Pause
--              │              │          Fork — Show changes Preview
--——————————————┼——————————————┼——————————————————————————————————
--         ⇪␣   │              │ play_or_pause
--         ⇧␣   │              │
--         ⌃␣   │              │              — change language layout
--         ⌥␣   │ nbsp         │         Music — Start Genius Shuffle
--         ⌘␣   │              │       Raycast — open Raycast
--——————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧␣   │    num0      │
{ chord = "num0",                           fn = "musicapp.play_pause" },
--        ⇪⌃␣   │              │
--        ⇪⌥␣   │              │
--        ⇪⌘␣   │              │
--        ⇧⌃␣   │              │
--        ⇧⌥␣   │              │
--        ⇧⌘␣   │              │
--        ⌃⌥␣   │              │
--        ⌃⌘␣   │              │              — emojis
--        ⌥⌘␣   │              │              — open Finder and focus Search this Mac
--——————————————┼——————————————┼——————————————————————————————————
--       ⇪⇧⌃␣   │              │ play_or_pause
--       ⇪⇧⌥␣   │              │
--       ⇪⇧⌘␣   │              │
--       ⇪⌃⌥␣   │              │
--       ⇪⌃⌘␣   │              │
--       ⇪⌥⌘␣   │              │
--       ⇧⌃⌥␣   │              │
--       ⇧⌃⌘␣   │              │
--       ⇧⌥⌘␣   │              │
--       ⌃⌥⌘␣   │              │
--              ┴              ┴
}
