return {
--    ╭—————╮
--    │  U  │
--    ╰—————╯
--
--         karabiner: no
--
--——————— chord ┬ en | ru | el ┬
--          u   │ u    г    υ  │
--——————————————┼——————————————┼——————————————————————————————————
--         ⇪u   │              │
--         ⇧u   │ U    Г    Υ  │
--         ⌃u   │              │
--         ⌥u   │ ѵ    ѵ­­    no │
--         ⌘u   │              │ Telegram — toggle underline for text
--——————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧u   │              │
--        ⇪⌃u   │              │
--        ⇪⌥u   │              │
--        ⇪⌘u   │              │
--        ⌘⇧u   │              │ ℝ — toggle case of text
--        ⇧⌃u   │              │
--        ⇧⌥u   │ Ѵ    Ѵ    Ξ  │ ℝ — show unit testing quick panel
--        ⇧⌘u   │              │
--        ⌃⌥u   │              │
--        ⌃⌘u   │              │ Music — show/hide lyrics panel
--        ⌥⌘u   │              │ Music — Show playing next queue
--              │              │ Yandex — view source code
--——————————————┼——————————————┼——————————————————————————————————
--       ⇪⇧⌃u   │              │
--       ⇪⇧⌥u   │              │
--       ⇪⇧⌘u   │              │
--       ⇪⌃⌥u   │              │
--       ⇪⌃⌘u   │              │
--       ⇪⌥⌘u   │              │
--       ⇧⌃⌥u   │              │
--       ⇧⌃⌘u   │              │
--       ⇧⌥⌘u   │              │
--       ⌃⌥⌘u   │              │
--              ┴              ┴
}
