return {
--    ╭—————╮
--    │  ↑  │    arrow up
--    ╰—————╯
--
--
--———————— chord ┬ en | ru | el ┬—————————— app — function ————————————————————
--           ↑   │       ↑      │      Telegram — edit last message
--               │              │          IINA — sound up 5%
--———————————————┼——————————————┼——————————————————————————————————
--          ⇪↑   │              │
--          ⇧↑   │              │              — select text up one line
--          ⌃↑   │              │              — show windows of current app
--          ⌥↑   │              │              — move line up
--               │              │         Rider — extend selection
--          ⌘↑   │              │         Music — increase volume
--                              │        VSCode — jump to breadcumbs
--———————————————┼——————————————┼——————————————————————————————————
--         ⇪⇧↑   │              │
--         ⇪⌃↑   │              │
--         ⇪⌥↑   │              │
--         ⇪⌘↑   │              │
--         ⇧⌃↑   │              │ FIX!!! should up volume up
--         ⇧⌥↑   │              │        VSCode — move line up
--         ⇧⌘↑   │ key_light_up │  — increase keyboard light (illumination_increment)
{ chord = "⌃⌥↑",                             fn = "window.fullscreen" },
--         ⌃⌘↑   │              │
--         ⌥⌘↑   │              │        VSCode — create cursor up
--———————————————┼——————————————┼——————————————————————————————————
--        ⇪⇧⌃↑   │              │
--        ⇪⇧⌥↑   │              │
--        ⇪⇧⌘↑   │              │
--        ⇪⌃⌥↑   │              │
--        ⇪⌃⌘↑   │              │
--        ⇪⌥⌘↑   │              │
--        ⇧⌃⌥↑   │              │
--        ⇧⌃⌘↑   │              │
--        ⇧⌥⌘↑   │              │
--        ⌃⌥⌘↑   │              │
--               ┴              ┴
}
