return {
--    ╭—————╮
--    │  W  │    close / up
--    ╰—————╯
--
--
--———————— chord ┬ en | ru | el ┬—————————— app — function ————————————————————
--           w   │ w    ц    ω  │   Browser Vim — toggle pin tab
--———————————————┼——————————————┼————————————————————————————————————
--          ⇪w   │      ↑       │              — up
--          ⇧w   │ W    Ц    Ω  │
--          ⌃w   │              │         Rider — close all notifications
--               │              │        VSCode — select window to switch
--          ⌥w   │      ⌥↑      │              — move line up
--               │              │         Rider — extend selection
--          ⌘w   │              │              — close current tab
--          ⇥w   │      ⌘[      │          IINA — multiply speed 0.5
--               │              │         Rider — navigate back
--               │              │        Finder — navigate back
--               │              │       Browser — navigate back
--               │              │         Music — navigate back
--———————————————┼——————————————┼————————————————————————————————————
--         ⇪⇧w   │      ⇧↑      │              — select line up
--         ⇪⌃w   │      ⌃↑      │              — show all windows
--         ⇪⌥w   │      ⌥↑      │              — move line up
--               │              │         Rider — extend selection
--         ⇪⌘w   │      ⌘↑      │        VSCode — jump to breadcumbs
--         ⇧⌃w   │      ⌘m      │              — minimize window
--         ⇧⌥w   │     ⇧⌥↑      │        VSCode — move line up
--         ⇧⌘w   │              │         Rider — close other tabs
--               │              │              — close window
{ chord = "⌃⌥w",                             fn = "window.fullscreen" },
--         ⌃⌘w   │              │ ???
--         ⌥⌘w   │              │          Mail — close all Mail windows
--               │              │        VSCode — toggle search whole word
--———————————————┼——————————————┼————————————————————————————————————
--        ⇪⇧⌃w   │  volume_up   │              — volume_increment
--        ⇪⇧⌥w   │              │
--        ⇪⇧⌘w   │ key_light_up │              — illumination_increment
--        ⇪⌃⌥w   │              │
--        ⇪⌃⌘w   │     ⌃⌘↑      │         Rider — navigate to up method
--        ⇪⌥⌘w   │     ⌥⌘↑      │        VSCode — clone caret up;
--               │              │         iTerm — focus pane above
--        ⇧⌃⌥w   │              │
--        ⇧⌃⌘w   │              │
--        ⇧⌥⌘w   │              │
--        ⌃⌥⌘w   │              │
--               ┴              ┴
}
