# Catppuccin Mocha colors for eza
export EZA_COLORS="
di=1;34:    # directory (bold blue)
ex=1;32:    # executable (bold green)
ln=1;35:    # symlink (bold magenta)
ur=34:      # user read
uw=34:      # user write
ux=34:      # user execute
gr=36:      # group read
gw=36:      # group write
gx=36:      # group execute
tr=37:      # truncated
sn=32:      # size number
nb=32:      # size unit
uu=35:      # user
un=31:      # user root
gu=34:      # group
gn=31:      # group root
ga=90:      # git added
gm=33:      # git modified
gd=31:      # git deleted
gv=36:      # git renamed
*.md=93:    # markdown files
*.yml=33:   # yaml files
*.json=33:  # json files
*.sh=32:    # shell scripts
*.rs=31:    # rust files
*.py=34:    # python files
*.js=33:    # javascript files
*.ts=34:    # typescript files
*.jsx=33:   # react files
*.tsx=34:   # react typescript files
*.css=36:   # css files
*.html=33:  # html files
*.zip=35:   # zip files
*.tar=35:   # tar files
*.gz=35:    # gzip files
*.7z=35:    # 7z files
"
