gui:
  authorColors:
    "servitola": "magenta"
  showRandomTip: true
git:
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  copyToClipboardCmd: "pbcopy < {{text}}"
  editPreset: "vscode"
  open: "open {{filename}}"
  shellFunctionsFile: ~/projects/dotfiles/zsh/aliases.zsh
