gui:
  authorColors:
    "servitola": "magenta"
  showRandomTip: true
git:
  parseEmoji: true
os:
  copyToClipboardCmd: "pbcopy < {{text}}"
  editPreset: "vscode"
  open: "open {{filename}}"
  shellFunctionsFile: ~/projects/dotfiles/zsh/aliases.zsh
