duti -s com.microsoft.VSCode .js all
duti -s com.microsoft.VSCode .json all
duti -s com.microsoft.VSCode .md all
duti -s com.microsoft.VSCode .sh all
duti -s com.microsoft.VSCode .css all
duti -s com.microsoft.VSCode .html all
duti -s com.microsoft.VSCode .scss all
duti -s com.microsoft.VSCode .ts all
duti -s com.microsoft.VSCode .tsx all
duti -s com.microsoft.VSCode .vue all
duti -s com.microsoft.VSCode .xml all
duti -s com.microsoft.VSCode .yaml all
duti -s com.microsoft.VSCode .yml all
duti -s com.microsoft.VSCode .jsx all
duti -s com.microsoft.VSCode .java all
duti -s com.microsoft.VSCode .py all
duti -s com.microsoft.VSCode .rb all
duti -s com.microsoft.VSCode .go all
duti -s com.microsoft.VSCode .php all
duti -s com.microsoft.VSCode .c all
duti -s com.microsoft.VSCode .cpp all
duti -s com.microsoft.VSCode .h all
duti -s com.microsoft.VSCode .hpp all
duti -s com.microsoft.VSCode .swift all
duti -s com.microsoft.VSCode .kt all
duti -s com.microsoft.VSCode .kts all
duti -s com.microsoft.VSCode .dart all
duti -s com.microsoft.VSCode .gradle all
duti -s com.microsoft.VSCode .properties all
duti -s com.microsoft.VSCode .conf all
duti -s com.microsoft.VSCode .config all
duti -s com.microsoft.VSCode .ini all
duti -s com.microsoft.VSCode .toml all
duti -s com.microsoft.VSCode .lock all
duti -s com.microsoft.VSCode .md all
duti -s com.microsoft.VSCode .mdx all
duti -s com.microsoft.VSCode .txt all
duti -s com.microsoft.VSCode .log all
duti -s com.microsoft.VSCode .csv all