name: Default
active_window_index: 0
windows:
  - active_tab_index: 0
    tabs:
      - title: AI
        layout:
          cwd: /Users/servitola/projects/dotfiles
          is_focused: true
          commands:
            - exec: aoe
        color: red
      - title: Web
        layout:
          cwd: /Users/servitola/projects/Spotware/ctradermobileweb
          is_focused: true
          commands:
            - exec: yarn install && yarn dev
        color: yellow
