-- AUTO-GENERATED by docs/keyboard/tools/gen_bundle_ids.py — do not edit.
-- Regenerate after adding app chords: python3 docs/keyboard/tools/gen_bundle_ids.py
-- Maps layout app names to bundle IDs for exact hs.application.get()
-- lookups; names in layout files stay the source of truth and the
-- runtime falls back to hs.application.find() for missing entries.
-- Unresolved (not installed at generation time): Claude
return {
    ["Activity Monitor"] = "com.apple.ActivityMonitor",
    ["Finder"] = "com.apple.finder",
    ["Firefox"] = "org.mozilla.firefox",
    ["Fork"] = "com.DanPristupov.Fork",
    ["Google Chrome"] = "com.google.Chrome",
    ["Hammerspoon"] = "org.hammerspoon.Hammerspoon",
    ["Heroes of the Storm"] = "com.blizzard.heroesofthestorm",
    ["Iina"] = "com.colliderli.iina",
    ["Marta"] = "org.yanex.marta",
    ["Music"] = "com.apple.Music",
    ["OrbStack"] = "dev.kdrag0n.MacVirt",
    ["Rider"] = "com.jetbrains.rider",
    ["Safari"] = "com.apple.Safari",
    ["Simulator"] = "com.apple.iphonesimulator",
    ["System Settings"] = "com.apple.systempreferences",
    ["Telegram"] = "ru.keepcoder.Telegram",
    ["Visual Studio Code"] = "com.microsoft.VSCode",
    ["VoiceInk"] = "com.prakashjoshipax.VoiceInk",
    ["WebStorm"] = "com.jetbrains.WebStorm",
    ["Workbot"] = "com.workbot2.app",
    ["XCode"] = "com.apple.dt.Xcode",
    ["Yandex"] = "ru.yandex.desktop.yandex-browser",
    ["Zap"] = "dev.zap.Zap",
    ["iTerm"] = "com.googlecode.iterm2",
    ["zoom.us"] = "us.zoom.xos",
}
