#!/usr/bin/env python3
"""Regenerate HotKeys.spoon/app_bundle_ids.lua from `app = "..."` layout entries.

Resolves each app name to a bundle ID via LaunchServices. Names in layout
files stay the source of truth; unresolved names fall back to fuzzy find
at runtime. Re-run (from repo root) after adding an app chord.
"""

import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
LAYOUT_DIR = REPO_ROOT / "hammerspoon/Spoons/HotKeys.spoon/layout/60%"
OUTPUT = REPO_ROOT / "hammerspoon/Spoons/HotKeys.spoon/app_bundle_ids.lua"

APP_RE = re.compile(r'app\s*=\s*"([^"]+)"')

# LaunchServices resolves some names to a launcher stub instead of the app
# process that actually runs (verified against set_language_on_app_focused.lua).
OVERRIDES = {
    "Heroes of the Storm": "com.blizzard.heroesofthestorm",  # not net.battle.bootstrapper
}


def collect_app_names() -> list[str]:
    names = set()
    for lua in sorted(LAYOUT_DIR.glob("*.lua")):
        names.update(APP_RE.findall(lua.read_text()))
    return sorted(names)


def resolve_bundle_id(name: str) -> str | None:
    try:
        out = subprocess.run(
            ["osascript", "-e", f'id of app "{name}"'],
            capture_output=True, text=True, timeout=15,
        )
    except subprocess.TimeoutExpired:
        return None
    bundle_id = out.stdout.strip()
    return bundle_id if out.returncode == 0 and bundle_id else None


def main() -> int:
    names = collect_app_names()
    resolved: dict[str, str] = {}
    unresolved: list[str] = []

    for name in names:
        bundle_id = OVERRIDES.get(name) or resolve_bundle_id(name)
        if bundle_id:
            resolved[name] = bundle_id
            print(f"  {name:<24} → {bundle_id}")
        else:
            unresolved.append(name)
            print(f"  {name:<24} → UNRESOLVED (runtime falls back to find)")

    lines = [
        "-- AUTO-GENERATED by docs/keyboard/tools/gen_bundle_ids.py — do not edit.",
    ]
    if unresolved:
        lines.append("-- Unresolved (not installed at generation time): "
                     + ", ".join(unresolved))
    lines.append("return {")
    for name, bundle_id in sorted(resolved.items()):
        lines.append(f'    ["{name}"] = "{bundle_id}",')
    lines.append("}")

    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"\nWrote {len(resolved)} entries to {OUTPUT.relative_to(REPO_ROOT)}"
          + (f" ({len(unresolved)} unresolved)" if unresolved else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
